version: '3'
services:
  adsoft-dev:
    build: . 
    buildargs: -t
    image: adsoft/adsoftsito
    container_name: adsoft-graphql-dev
    command: python manage.py runserver --setting=settings.develop 0.0.0.0:8080
    volumes:
    - .:/hackernews
    ports:
    - "8080:8080"
    env_file:
      - .env
