apiVersion: apps/v1
kind: Deployment
metadata:
  name: adsoftsito
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adsoftsito
  template:
    metadata:
      labels:
        app: adsoftsito
    spec:
      containers:
      - image: adsoft/hackernews:latest
        name: adsoftsito

---

apiVersion: v1
kind: Service
metadata:
  name: adsoftsito
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "adsoftsito"
    port: 8080
  selector:
    app: adsoftsito
