apiVersion: apps/v1
kind: Deployment
metadata:
  name: {model_name}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {model_name}-server
  template:
    metadata:
      labels:
        app: {model_name}-server
    spec:
      containers:
      - image: okteto.dev/adsoftsito:latest
        name: {docker_user}
        envFrom:
        - configMapRef:
            name: {docker_user}-config
        livenessProbe:
          httpGet:
            path: /ht/
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: model_name}-service
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: model_name}-service
    port: 8080
  selector:
    app: model_name}-server
